### ISSUE TITLE
General getTotalConcentration method

### ISSUE THREAD

**Issue by sblondel** [ORNL-Fusion/xolotl#136]
Gather all the ``network.getTotalConcentration`` methods under a general one that takes tuples as arguments and return a tuple of double. For each quantity, the user needs to specify the keyword, species, and minimum size.

Here are the methods/keywords:
- ``getTotalConcentration`` / **total**: simple sum over concentration
- ``getTotalAtomConcentration`` / **atom**: sum over concentration times the composition of the species
- ``getTotalRadiusConcentration`` / **radius**: sum over concentration times the radius
- ``getTotalVolumeFraction`` / **volume**: sum over the concentration times the volume of a sphere with this radius
- ``getTotalTrappedAtomConcentration`` / **trapped**: like **atom** but only if the species is part of a cluster with at least one vacancy

**Comment by PhilipFackler** [comment]
This get a bit more interesting since the first three in that list are virtual functions available through `IReactionNetwork`, whereas the last two are not. On top of this `IPSIReactionNetwork` has an virtual function called `getTotalTrappedHeliumConcentration`, the implementation of which in `PSIReactionNetwork` calls (the non-virtual) `getTotalTrappedAtomConcentration`.
