### ISSUE TITLE
Compile error with recent boost

### ISSUE THREAD

**Issue by sblondel** [ORNL-Fusion/xolotl#146]
`xolotl/core/include/xolotl/core/flux/CustomFitFluxHandler.h:111:7: error: no member named 'ifstream' in namespace 'boost::filesystem'

                fs::ifstream paramFile(profileFilePath);`

**Comment by PhilipFackler** [comment]
Workaround is to use `std::ifstream` and the `.string()` or `.native()` member of `fs::path`.

Long-term, we need to drop boost::filesystem in favor of std::filesystem. This has been the plan for a while, but we've been waiting to make sure C++17 was "fully" supported on all the machines/compilers we use. For example, this would not necessarily be a straightforward change since the default compiler is gcc 8.5, which only "experimentally" supports the filesystem library and requires a separate library to be linked in.

**Comment by sblondel** [comment]
Solved by #150 .
