### ISSUE TITLE
kokkos transplant consultation

### ISSUE THREAD

**Issue by liyujin1999** [ORNL-Fusion/xolotl#169]
xedefect.h  Header file:
	class XeDefect
	{
		public:
				class ReactionPair
				{
				public:              
						double a0, a1;
				};
			int id;
			vector<double> diffusionCoefficient;
			vector<ReactionPair> reactionPairs;
	}
	
	defectmanager.h  Header file:
	class DefectManager
	{
		public：
			vector<XeDefect_KOKKOS> xedefects;
		void init(){
			for(int i=0; i<5; i++){
				xedefects[i].id = i;
				xedefects[i].diffusionCoefficient = {1,2,3};
				for(int j=0; j<3; j++){
					xedefects[i].reactionPairs[j].a0 = j;
					xedefects[i].reactionPairs[j].a1 = j;
				}
			}
		}
	}	
	
	
	xedefect_kokkos.h  Header file:
	class XeDefect_KOKKOS
	{
		public:
				class ReactionPair
				{
				public:              
						double a0, a1;
				};
			int id;
			Kokkos::View<double*> diffusionCoefficient;
			Kokkos::View<ReactionPair*> reactionPairs;
	}
	
	defectmanager_kokkos.h  Header file:
	class DefectManager_KOKKOS
	{
		public：
			Kokkos::View<XeDefect_KOKKOS> xedefects;
		void init(){
			//Supplementary code, initialization xedefects
		}
	}

The defectmanager class, which is the management class of the XeDefect class and contains the XeDefect object, has initialized xedefects using a function init() in defectManager.h. I am now using kokkos to do a code port, rewriting the vector data into kokkos View,I want to initialize xedefects in the init() method in defectmanager_kokkos.h, Initialization of xedefects in DefectManager_KOKKOS.h requires the use of xedefects data in DefectManager.h. And the size of kokkos::View type data in XeDefect_KOKKOS.h and DefectManager_KOKKOS.h cannot be specified directly with constructors, and should be dynamically set according to the data of xedefects in defectManager_kokkos. h. The default execution space is on the GPU, how do I implement init() code in defectmanager_kokkos.h, please give me some suggestions, thank you very much!

**Comment by liyujin1999** [comment]
vector<XeDefect_KOKKOS> xedefects in defectmanager.h  Header file; vector<XeDefect> xedefects;

**Comment by PhilipFackler** [comment]
Doing a View inside another View gets complicated. But (based on your code above) if the sizes of the XeDefect members are known beforehand, you could do this:
```
class XeDefect
{
public:
    class ReactionPair
    {
        public:              
        double a0, a1;
    };
    int id;
    Kokkos::Array<double, 3> diffusionCoefficient;
    Kokkos::Array<ReactionPair, 3> reactionPairs;
};

class DefectManager
{
	public：
		Kokkos::View<XeDefect[5]> xedefects;
	void init(){
		Kokkos::parallel_for(5, KOKKOS_LAMBDA (int i) {
			xedefects[i].id = i;
			xedefects[i].diffusionCoefficient = {1,2,3};
			for(int j=0; j<3; j++){
				xedefects[i].reactionPairs[j].a0 = j;
				xedefects[i].reactionPairs[j].a1 = j;
			}
		});
	}
};
```

If the `5` in DefectManager should be programmable, you would use `Kokkos::View<XeDefect*> xedefects;` and allocate with `xedefects = Kokkos::View<XeDefect*>("defects", numberOfDefects);`.

Now, if the `3` in XeDefect should also be variable, that gets a little more complicated. In that case, I would let DefectManager own a master array of all the diffusion coefficients (for example). So you would need to know the total number of coefficients and allocate them all in one. If the number of coefficients per defect is constant, this could be a 2D View like `allCoefficients = Kokkos::View<double**>("coefficients", numberOfDefects, nCoeffPerDefect);`. Otherwise, compute the total number and just use a 1D view.

Then, each defect could have a "subview" which is looking at just its portion of the master array. To do this correctly you have to let the compiler deduce the type of the subview (since the result could be contiguous or strided). Kokkos has a type to help (a little) with this. So, if you use the 2D view: `Kokkos::Subview<Kokkos::View<double**>, int, decltype(Kokkos::ALL)> diffusionCoefficient;`. If you use the 1D view: `Kokkos::Subview<Kokkos::View<double*>, std::pair<int, int>> diffusionCoefficient;`. (The template arguments correspond to the parameters you would use to assign using the `subview` function.

If it gets more complicated than this, it's probably more of a question for the kokkos community. And in my experience they tend to be quite responsive and helpful.

Hope that helps!

**Comment by liyujin1999** [comment]
Thank you very much for your idea. Taking diffusionCoefficient as an example, the number of coefficients per defect is not a constant. I want to allocate sizes to these view variables in each defect (and in device-side (GPU) memory). How can I do it? ? I hope you can give me some ideas, thank you very much

**Comment by PhilipFackler** [comment]
You would have to loop over your defects to count the number of entries. This could be done with a `Kokkos::parallel_reduce`. You could use a temporary `View` (`numberOfDefects + 1` long) to store the starting index of the list of entries for each defect. This can be computed by first storing the count per defect in said `View` and then performing a `Kokkos::parallel_scan` on it (you can look up examples of this). Once you have this temporary index view and have allocated the `allCoefficients` view, you can use a `Kokkos::parallel_for` to assign the `subview` to each defect using the pair `{ids[i], ids[i+1]}` as the range. Each defect would then have a unique array of coefficients to read and write, all of which are portions of the one contiguous allocation.

**Comment by liyujin1999** [comment]
Thank you very much for your help, I understand
