### ISSUE TITLE
Write final multi-instance output data at end of input simulation time

### ISSUE THREAD

**Issue by LP-Nick** [ORNL-Fusion/xolotl#192]
Currently, the data is saved to the xolotlStop.h5 files at the penultimate time interval set by the -start_stop option rather than the final interval. It would be useful to have the data from the final interval. For example, if I am running Xolotl to 1000s with a -start_stop interval of 100s, then what I actually have saved is the data at 900s. In the case that I want to restart at 1000s with new simulation conditions, I need to have the data at 1000s.

**Comment by sblondel** [comment]
@LP-Nick it seems like the issue is that the multi-instances time stepper doesn't step over the final time. To change that, can you try changing the condition in https://github.com/ORNL-Fusion/xolotl/blob/b4605b1734b60899b43dea76110a11f9db3f8d7f/xolotl/util/src/TimeStepper.cpp#L58 to `_previousTime < _endTime` ?
