### ISSUE TITLE
Fix compability issue for xolotStop.h5 file

### ISSUE THREAD

**Issue by jguterl** [ORNL-Fusion/xolotl#68]
Xolotl cannot restart from a XolotStop.h5 produced with a older version due to missing fields (like nHeliumSurface).
I suggest removing the following block from Monitor.cpp and always write xolotStop.h5 from scratch (was it done for speed? can we actually copy from existing xolotStop.h5 once created)?:

		if (not srcFileName.empty()) {
			// Copy the network from the given file.
			// Note that we do this using a single-process
			// communicator because the HDF5 copy operation
			// is not parallelized and gives very poor performance
			// if used with a file opened for parallel access.
			io::XFile srcFile(srcFileName, MPI_COMM_SELF,
				io::XFile::AccessMode::OpenReadOnly);

			// Check if given file even has a network group.
			auto srcNetGroup = srcFile.getGroup<io::XFile::NetworkGroup>();
			if (srcNetGroup) {
				// Given file has a network group.  Copy it.
				// First open the checkpoint file using a single-process
				// communicator...
				io::XFile checkpointFile(targetFileName, MPI_COMM_SELF,
					io::XFile::AccessMode::OpenReadWrite);

				// ...then do the copy.
				srcNetGroup->copyTo(checkpointFile);
			}
		}

**Comment by sblondel** [comment]
The compatibility issue from missing fields is not related to the network group in the HDF5 restart file, the missing fields are usually in the concentration group.
Compatibility could be fixed by checking whether the field exists in the file before trying to access it.
Is there another reason why xolotlStop.h5 should be written from scratch? (yes, the network group is directly copied from the input restart file to the output restart file to save time)

**Comment by jguterl** [comment]
Agreed. The solution proposed to fix that issue is to update the networkFile from which xolotl is restarting from using:
https://github.com/jguterl/pyXolotl/blob/master/examples/update_h5file.py
