### ISSUE TITLE
cannot get list of parameters from exec on CORI

### ISSUE THREAD

**Issue by jguterl** [ORNL-Fusion/xolotl#92]
/project/projectdirs/atom/atom-install-cori/xolotl/xolotl-bursting-build/xolotl/xolotl --help

      --------------------------------------------------------------------------------
      -------------Kokkos command line arguments--------------------------------------
      --------------------------------------------------------------------------------
      The following arguments exist also without prefix 'kokkos' (e.g. --help).
      The prefixed arguments will be removed from the list by Kokkos::initialize(),
      the non-prefixed ones are not removed. Prefixed versions take precedence over
      non prefixed ones, and the last occurrence of an argument overwrites prior
      settings.

      --kokkos-help                  : print this message
      --kokkos-disable-warnings      : disable kokkos warning messages
      --kokkos-tune-internals        : allow Kokkos to autotune policies and declare
                                       tuning features through the tuning system. If
				         left off, Kokkos uses heuristics
      --kokkos-threads=INT           : specify total number of threads or
                                       number of threads per NUMA region if
                                       used in conjunction with '--numa' option.
      --kokkos-numa=INT              : specify number of NUMA regions used by process.
      --kokkos-device-id=INT         : specify device id to be used by Kokkos.
      --kokkos-num-devices=INT[,INT] : used when running MPI jobs. Specify number of
                                       devices per node to be used. Process to device
                                       mapping happens by obtaining the local MPI rank
                                       and assigning devices round-robin. The optional
                                       second argument allows for an existing device
                                       to be ignored. This is most useful on workstations
                                       with multiple GPUs of which one is used to drive
                                       screen output.
      --------------------------------------------------------------------------------

[Thu Dec 16 12:42:48 2021] [unknown] Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(537): 
MPID_Init(246).......: channel initialization failed
MPID_Init(647).......:  PMI2 init failed: 1 
Aborted

**Comment by jguterl** [comment]
it is possible to have a fix to execute it without srun?

**Comment by sblondel** [comment]
@jguterl It seems to me that this is related to Cori limitations. Did you try from a job or an interactive session?

**Comment by rothpc** [comment]
@jguterl, @sblondel - I suspect it is necessary to launch this "--help" process via srun to avoid the MPI_Init() error.  It's been a while since I've used Cori and I don't remember whether it uses separate batch nodes to run batch scripts and interactive shells, but I think MPI_Init() is expecting to have some information from the resource manager that it isn't getting without running via srun.

To @jguterl's question about whether it is possible to make it so that one could ask for help without running under srun - I think it is possible but difficult and definitely kludgy.   Because MPI_Init() has the potential to strip out options that the MPI library understands before letting the rest of the program see the command line, supporting that help behavior would require parsing the command line twice - once before the program calls MPI_Init() looking for '-h' and/or '--help', and ignoring everything else, and then once after MPI_Init() returns.  (Probably after Kokkos is initialized also since it can do the same thing to argc/argv, and possibly also PETSc's initialization.)

Also - what would the behavior be if someone did 'srun -n 8 xolotl --help'?  Since MPI wouldn't be initialized yet at the time the help option was handled, it wouldn't be possible to make it so that only one process would output the help messages in a portable way.  So every process would output the full help message, and without any synchronization between them the output would most likely be a mess.

Note that there are some systems where it is possible to run an single-process MPI program without a parallel launcher, and the MPI library defaults that process to be rank 0.  My experience though, is that it rarely works that way on the big HPC facility's systems.
